import http from "http";

const port = 3000;

const server = http.createServer((request, response) => {
    response.setHeader('Access-Control-Allow-Origin', '*');
    response.setHeader('Access-Control-Request-Method', '*');
    response.setHeader('Access-Control-Allow-Methods', 'OPTIONS, GET');
    response.setHeader('Access-Control-Allow-Headers', '*');
    if (request.method === 'OPTIONS') {
        response.writeHead(200);
        response.end();
        return;
    }

    response.end(JSON.stringify([{
        "id": 1,
        "firstName": "Livvy",
        "lastName": "Shewon",
        "email": "lshewon0@privacy.gov.au",
        "gender": "Female",
        "ipAddress": "74.235.96.203"
    }, {
        "id": 2,
        "firstName": "Alair",
        "lastName": "McMearty",
        "email": "amcmearty1@walmart.com",
        "gender": "Male",
        "ipAddress": "4.16.198.186"
    }, {
        "id": 3,
        "firstName": "Otes",
        "lastName": "Corwin",
        "email": "ocorwin2@mashable.com",
        "gender": "Male",
        "ipAddress": "158.190.126.185"
    }, {
        "id": 4,
        "firstName": "Darbie",
        "lastName": "Lettice",
        "email": "dlettice3@odnoklassniki.ru",
        "gender": "Female",
        "ipAddress": "158.19.71.30"
    }, {
        "id": 5,
        "firstName": "Nikki",
        "lastName": "Dawdary",
        "email": "ndawdary4@imdb.com",
        "gender": "Female",
        "ipAddress": "210.151.191.217"
    }, {
        "id": 6,
        "firstName": "Jared",
        "lastName": "Sitlinton",
        "email": "jsitlinton5@linkedin.com",
        "gender": "Male",
        "ipAddress": "159.69.220.107"
    }, {
        "id": 7,
        "firstName": "Agnella",
        "lastName": "Pyffe",
        "email": "apyffe6@digg.com",
        "gender": "Female",
        "ipAddress": "114.208.146.138"
    }, {
        "id": 8,
        "firstName": "Consuela",
        "lastName": "Leve",
        "email": "cleve7@yellowbook.com",
        "gender": "Female",
        "ipAddress": "52.88.175.43"
    }, {
        "id": 9,
        "firstName": "Adelind",
        "lastName": "Bison",
        "email": "abison8@wikipedia.org",
        "gender": "Female",
        "ipAddress": "90.214.49.213"
    }, {
        "id": 10,
        "firstName": "Dolph",
        "lastName": "Fike",
        "email": "dfike9@paypal.com",
        "gender": "Male",
        "ipAddress": "48.82.238.224"
    }, {
        "id": 11,
        "firstName": "Lacie",
        "lastName": "Gribbell",
        "email": "lgribbella@mediafire.com",
        "gender": "Female",
        "ipAddress": "28.208.132.45"
    }, {
        "id": 12,
        "firstName": "Erny",
        "lastName": "Revely",
        "email": "erevelyb@wsj.com",
        "gender": "Male",
        "ipAddress": "204.136.134.246"
    }, {
        "id": 13,
        "firstName": "Iseabal",
        "lastName": "Skurray",
        "email": "iskurrayc@google.es",
        "gender": "Female",
        "ipAddress": "114.142.54.23"
    }, {
        "id": 14,
        "firstName": "Maisie",
        "lastName": "Ramos",
        "email": "mramosd@diigo.com",
        "gender": "Female",
        "ipAddress": "230.34.0.11"
    }, {
        "id": 15,
        "firstName": "Ford",
        "lastName": "Hullock",
        "email": "fhullocke@home.pl",
        "gender": "Male",
        "ipAddress": "138.88.110.11"
    }, {
        "id": 16,
        "firstName": "Reggis",
        "lastName": "Garley",
        "email": "rgarleyf@buzzfeed.com",
        "gender": "Male",
        "ipAddress": "13.46.10.139"
    }, {
        "id": 17,
        "firstName": "Manon",
        "lastName": "Learmount",
        "email": "mlearmountg@google.pl",
        "gender": "Female",
        "ipAddress": "97.97.187.29"
    }, {
        "id": 18,
        "firstName": "Annette",
        "lastName": "Coggeshall",
        "email": "acoggeshallh@networkadvertising.org",
        "gender": "Female",
        "ipAddress": "15.238.187.60"
    }, {
        "id": 19,
        "firstName": "Tab",
        "lastName": "Littrell",
        "email": "tlittrelli@odnoklassniki.ru",
        "gender": "Male",
        "ipAddress": "228.251.247.144"
    }, {
        "id": 20,
        "firstName": "Florance",
        "lastName": "Wackley",
        "email": "fwackleyj@xing.com",
        "gender": "Female",
        "ipAddress": "29.22.227.115"
    }, {
        "id": 21,
        "firstName": "Dewain",
        "lastName": "Mackneis",
        "email": "dmackneisk@1688.com",
        "gender": "Male",
        "ipAddress": "45.127.59.52"
    }, {
        "id": 22,
        "firstName": "Evangeline",
        "lastName": "Armfield",
        "email": "earmfieldl@yahoo.co.jp",
        "gender": "Female",
        "ipAddress": "208.40.150.85"
    }, {
        "id": 23,
        "firstName": "Nessi",
        "lastName": "Gillford",
        "email": "ngillfordm@bluehost.com",
        "gender": "Female",
        "ipAddress": "52.86.186.25"
    }, {
        "id": 24,
        "firstName": "Freeman",
        "lastName": "Allam",
        "email": "fallamn@so-net.ne.jp",
        "gender": "Male",
        "ipAddress": "49.250.31.51"
    }, {
        "id": 25,
        "firstName": "Renato",
        "lastName": "Martonfi",
        "email": "rmartonfio@mlb.com",
        "gender": "Male",
        "ipAddress": "108.35.89.87"
    }, {
        "id": 26,
        "firstName": "Layney",
        "lastName": "Cometson",
        "email": "lcometsonp@csmonitor.com",
        "gender": "Female",
        "ipAddress": "23.214.103.239"
    }, {
        "id": 27,
        "firstName": "Heddie",
        "lastName": "Habbon",
        "email": "hhabbonq@webeden.co.uk",
        "gender": "Female",
        "ipAddress": "17.130.250.184"
    }, {
        "id": 28,
        "firstName": "Nolan",
        "lastName": "MacNeachtain",
        "email": "nmacneachtainr@mediafire.com",
        "gender": "Male",
        "ipAddress": "28.21.50.242"
    }, {
        "id": 29,
        "firstName": "Arleen",
        "lastName": "Trusse",
        "email": "atrusses@google.com",
        "gender": "Female",
        "ipAddress": "211.51.245.237"
    }, {
        "id": 30,
        "firstName": "Arnuad",
        "lastName": "O'Carran",
        "email": "aocarrant@tripod.com",
        "gender": "Male",
        "ipAddress": "98.44.204.140"
    }, {
        "id": 31,
        "firstName": "Alair",
        "lastName": "Micheu",
        "email": "amicheuu@multiply.com",
        "gender": "Male",
        "ipAddress": "117.14.192.19"
    }, {
        "id": 32,
        "firstName": "Ketty",
        "lastName": "Dabnot",
        "email": "kdabnotv@about.me",
        "gender": "Female",
        "ipAddress": "122.240.195.137"
    }, {
        "id": 33,
        "firstName": "Mord",
        "lastName": "Colloby",
        "email": "mcollobyw@pbs.org",
        "gender": "Male",
        "ipAddress": "210.190.29.243"
    }, {
        "id": 34,
        "firstName": "Lynn",
        "lastName": "Clausner",
        "email": "lclausnerx@sfgate.com",
        "gender": "Female",
        "ipAddress": "168.208.59.243"
    }, {
        "id": 35,
        "firstName": "Tersina",
        "lastName": "Smedley",
        "email": "tsmedleyy@naver.com",
        "gender": "Female",
        "ipAddress": "52.203.17.240"
    }, {
        "id": 36,
        "firstName": "Dasya",
        "lastName": "Hryniewicz",
        "email": "dhryniewiczz@zimbio.com",
        "gender": "Female",
        "ipAddress": "24.3.239.49"
    }, {
        "id": 37,
        "firstName": "Eberhard",
        "lastName": "Skakunas",
        "email": "eskakunas10@sogou.com",
        "gender": "Male",
        "ipAddress": "230.109.145.179"
    }, {
        "id": 38,
        "firstName": "Elwin",
        "lastName": "Corain",
        "email": "ecorain11@purevolume.com",
        "gender": "Male",
        "ipAddress": "189.66.13.131"
    }, {
        "id": 39,
        "firstName": "Dwain",
        "lastName": "Prudham",
        "email": "dprudham12@shutterfly.com",
        "gender": "Male",
        "ipAddress": "225.155.161.24"
    }, {
        "id": 40,
        "firstName": "Eldredge",
        "lastName": "Merrikin",
        "email": "emerrikin13@goodreads.com",
        "gender": "Male",
        "ipAddress": "224.224.8.195"
    }, {
        "id": 41,
        "firstName": "Florry",
        "lastName": "Strewther",
        "email": "fstrewther14@indiatimes.com",
        "gender": "Female",
        "ipAddress": "124.33.43.174"
    }, {
        "id": 42,
        "firstName": "Lonee",
        "lastName": "Aslet",
        "email": "laslet15@opensource.org",
        "gender": "Female",
        "ipAddress": "81.64.93.93"
    }, {
        "id": 43,
        "firstName": "Nisse",
        "lastName": "Kaesmans",
        "email": "nkaesmans16@hp.com",
        "gender": "Female",
        "ipAddress": "81.98.11.83"
    }, {
        "id": 44,
        "firstName": "Sasha",
        "lastName": "Le Port",
        "email": "sleport17@hp.com",
        "gender": "Male",
        "ipAddress": "136.148.56.86"
    }, {
        "id": 45,
        "firstName": "Ali",
        "lastName": "Shaddick",
        "email": "ashaddick18@boston.com",
        "gender": "Male",
        "ipAddress": "121.192.180.130"
    }, {
        "id": 46,
        "firstName": "Wolfie",
        "lastName": "Brimblecombe",
        "email": "wbrimblecombe19@timesonline.co.uk",
        "gender": "Male",
        "ipAddress": "135.199.6.136"
    }, {
        "id": 47,
        "firstName": "Faustine",
        "lastName": "Ashford",
        "email": "fashford1a@naver.com",
        "gender": "Female",
        "ipAddress": "31.197.81.58"
    }, {
        "id": 48,
        "firstName": "Camilla",
        "lastName": "Cracknell",
        "email": "ccracknell1b@npr.org",
        "gender": "Female",
        "ipAddress": "197.80.238.247"
    }, {
        "id": 49,
        "firstName": "Agatha",
        "lastName": "Riglar",
        "email": "ariglar1c@slashdot.org",
        "gender": "Female",
        "ipAddress": "209.74.203.73"
    }, {
        "id": 50,
        "firstName": "Christel",
        "lastName": "Mimmack",
        "email": "cmimmack1d@hp.com",
        "gender": "Female",
        "ipAddress": "88.214.71.226"
    }, {
        "id": 51,
        "firstName": "Gillian",
        "lastName": "Coulbeck",
        "email": "gcoulbeck1e@bloglines.com",
        "gender": "Female",
        "ipAddress": "62.43.89.169"
    }, {
        "id": 52,
        "firstName": "Gene",
        "lastName": "Giovannacci",
        "email": "ggiovannacci1f@jigsy.com",
        "gender": "Male",
        "ipAddress": "153.160.255.228"
    }, {
        "id": 53,
        "firstName": "Jenni",
        "lastName": "Chillistone",
        "email": "jchillistone1g@csmonitor.com",
        "gender": "Female",
        "ipAddress": "240.80.68.67"
    }, {
        "id": 54,
        "firstName": "Tabor",
        "lastName": "Ladley",
        "email": "tladley1h@nps.gov",
        "gender": "Male",
        "ipAddress": "152.128.148.195"
    }]));
});

server.listen(port, () => {
    console.log(`server is listening on ${port}`)
});
